#ifndef _NTG_OBJECT_TYPES_H
#define _NTG_OBJECT_TYPES_H

#include <stdbool.h>

#define NTG_OBJECT_WIDGET 0
#define NTG_OBJECT_LABEL (NTG_OBJECT_WIDGET + 1)
#define NTG_OBJECT_COLOR_BLOCK (NTG_OBJECT_WIDGET + 2)
#define NTG_OBJECT_PROG_BAR (NTG_OBJECT_WIDGET + 3)
#define NTG_OBJECT_BOX (NTG_OBJECT_WIDGET + 10)
#define NTG_OBJECT_BORDER_BOX (NTG_OBJECT_WIDGET + 11)

#define NTG_OBJECT_DECORATOR 1000

#endif // _NTG_OBJECT_TYPES_H
