#ifndef _NTG_OBJECT_TYPES_H_
#define _NTG_OBJECT_TYPES_H_

#include <stdbool.h>

#define NTG_OBJECT_WIDGET 0
#define NTG_OBJECT_LABEL (NTG_OBJECT_WIDGET + 1)
#define NTG_OBJECT_COLOR_BLOCK (NTG_OBJECT_WIDGET + 2)
#define NTG_OBJECT_PROG_BAR (NTG_OBJECT_WIDGET + 3)
#define NTG_OBJECT_BOX (NTG_OBJECT_WIDGET + 10)
#define NTG_OBJECT_BORDER_BOX (NTG_OBJECT_WIDGET + 11)

#define NTG_OBJECT_DECOR 1000
#define NTG_OBJECT_PADDING (NTG_OBJECT_DECOR + 1001)
#define NTG_OBJECT_BORDER (NTG_OBJECT_DECOR + 1002)

#endif // _NTG_OBJECT_TYPES_H_
