#ifndef _NTG_STATUS_H_
#define _NTG_STATUS_H_

typedef int ntg_status;

#define NTG_STATUS_BASE 2000
#define NTG_SUCCESS (NTG_STATUS_BASE + 0)
#define NTG_ERR_UNEXPECTED (NTG_STATUS_BASE + 1)
#define NTG_ERR_INVALID_ARG (NTG_STATUS_BASE + 2)
#define NTG_ERR_MAX_THREAD (NTG_STATUS_BASE + 3)
#define NTG_ERR_ALLOC_FAIL (NTG_STATUS_BASE + 4)

#endif // _NTG_STATUS_H_
