#ifndef NTG_STATUS_H
#define NTG_STATUS_H

#define NTG_STATUS_BASE 2000
#define NTG_SUCCESS (NTG_STATUS_BASE + 0)
#define NTG_ERR_UNEXPECTED (NTG_STATUS_BASE + 1)
#define NTG_ERR_INVALID_ARG (NTG_STATUS_BASE + 2)
#define NTG_ERR_MAX_THREAD (NTG_STATUS_BASE + 3)
#define NTG_ERR_ALLOC_FAIL (NTG_STATUS_BASE + 4)

#define NTG_ERR_STAGE_HAS_LOOP (NTG_STATUS_BASE + 100)

#define NTG_ERR_THREAD_SPAWN (NTG_STATUS_BASE + 101)

#define NTG_ERR_LOOP_RUNNING (NTG_STATUS_BASE + 102)

#endif // NTG_STATUS_H
