#ifndef NTG_STATUS_H
#define NTG_STATUS_H

#define NTG_STATUS_BASE 2000
#define NTG_SUCCESS (NTG_STATUS_BASE + 0)
#define NTG_ERR_UNEXPECTED (NTG_STATUS_BASE + 1)
#define NTG_ERR_INVALID_ARG (NTG_STATUS_BASE + 2)
#define NTG_ERR_MAX_THREAD (NTG_STATUS_BASE + 3)
#define NTG_ERR_ALLOC_FAIL (NTG_STATUS_BASE + 4)
#define NTG_ERR_INVALID_TYPE (NTG_STATUS_BASE + 6)
#define NTG_ERR_BAD_VTABLE (NTG_STATUS_BASE + 7)

#define NTG_ERR_STAGE_HAS_LOOP (NTG_STATUS_BASE + 100)

#define NTG_ERR_THREAD_SPAWN (NTG_STATUS_BASE + 101)

#define NTG_ERR_LOOP_RUNNING (NTG_STATUS_BASE + 102)

#define NTG_ERR_MAX_ANCHORED (NTG_STATUS_BASE + 103)
#define NTG_ERR_MAX_CHILDREN (NTG_STATUS_BASE + 104)

#define NTG_ERR_PLATFORM_NO_LOOP (NTG_STATUS_BASE + 105)

#define NTG_ERR_SCENE_EMPTY (NTG_STATUS_BASE + 107)
#define NTG_ERR_SCOPE_NOT_IN_SCENE (NTG_STATUS_BASE + 108)

#endif // NTG_STATUS_H
