#ifndef _NTG_EVENT_SOURCE_ADAPTERS_H_
#define _NTG_EVENT_SOURCE_ADAPTERS_H_

#define NTG_EVENT_SOURCE_ADAPTER 0x01
#define NTG_STAGE_EVENT_SOURCE_ADAPTER 0x02

#endif // _NTG_EVENT_SOURCE_ADAPTERS_H_
